-- MySQL Script generated by MySQL Workbench
-- Sun Jun  9 20:08:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eer proyecto_aulas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eer proyecto_aulas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eer proyecto_aulas` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema proyecto_aulas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto_aulas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_aulas` DEFAULT CHARACTER SET utf8mb3 ;
USE `eer proyecto_aulas` ;

-- -----------------------------------------------------
-- Table `proyecto_aulas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_aulas`.`usuarios` (
  `dni` INT NOT NULL,
  `Nombre_Completo` VARCHAR(45) NOT NULL,
  `Cargo` ENUM('Docente', 'Autoridad', 'Alumno') NULL DEFAULT NULL,
  `Materia` VARCHAR(45) NULL DEFAULT NULL,
  `Mail` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `eer proyecto_aulas`.`Telefonos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eer proyecto_aulas`.`Telefonos` (
  `DNI` INT NOT NULL,
  `Telefono` INT NOT NULL,
  PRIMARY KEY (`DNI`, `Telefono`),
  CONSTRAINT `dni`
    FOREIGN KEY (`DNI`)
    REFERENCES `proyecto_aulas`.`usuarios` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `proyecto_aulas` ;

-- -----------------------------------------------------
-- Table `proyecto_aulas`.`edificio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_aulas`.`edificio` (
  `idedificio` INT NOT NULL,
  `NombreReal` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `Cantidad_Pisos` INT NOT NULL,
  PRIMARY KEY (`idedificio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_aulas`.`aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_aulas`.`aulas` (
  `idAulas` INT NOT NULL,
  `idEdificio` INT NOT NULL,
  `Piso` INT NOT NULL,
  `Nombre_Real` VARCHAR(45) NOT NULL,
  `Capacidad` INT NOT NULL,
  `Emision_en_vivo` BIT(1) NULL DEFAULT NULL,
  `Proyector` BIT(1) NULL DEFAULT NULL,
  `Tipo_Aula` ENUM('Taller', 'Auditorio', 'Tradicional') NOT NULL,
  PRIMARY KEY (`idAulas`, `idEdificio`),
  INDEX `idedificio_idx` (`idEdificio` ASC) VISIBLE,
  CONSTRAINT `idedificio`
    FOREIGN KEY (`idEdificio`)
    REFERENCES `proyecto_aulas`.`edificio` (`idedificio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_aulas`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_aulas`.`reserva` (
  `DNI` INT NOT NULL,
  `idaula` INT NOT NULL,
  `Horario_Inicio` SET('7:00', '8:00', '9:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00', '21:00') NOT NULL,
  `Horario_Finalizacion` SET('8:00', '9:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00', '21:00', '22:00') NOT NULL,
  PRIMARY KEY (`DNI`, `idaula`, `Horario_Inicio`),
  INDEX `idaulas_idx` (`idaula` ASC) VISIBLE,
  CONSTRAINT `DNI`
    FOREIGN KEY (`DNI`)
    REFERENCES `proyecto_aulas`.`usuarios` (`dni`),
  CONSTRAINT `idaulas`
    FOREIGN KEY (`idaula`)
    REFERENCES `proyecto_aulas`.`aulas` (`idAulas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_aulas`.`Telefonos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_aulas`.`Telefonos` (
  `DNI` INT NOT NULL,
  `Telefono` INT NOT NULL,
  PRIMARY KEY (`DNI`, `Telefono`),
  CONSTRAINT `dni`
    FOREIGN KEY (`DNI`)
    REFERENCES `proyecto_aulas`.`usuarios` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
